// Day-7 dish database: 200+ common desi dishes with realistic per-serving
// nutrition estimates (home/restaurant portions) + Urdu names + categories.
// Used by prisma/seed.ts and the /dishes browse/search page.
// Values are estimates — good enough for v1 tracking; refined over time.
import type { DishCategory } from "../lib/dishes";

export interface DishSeed {
  name: string;
  nameUrdu: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  servingSize: string;
  category: DishCategory;
}

export const DISHES: DishSeed[] = [
  // ---------- Breads ----------
  { name: "Roti (Tandoori)", nameUrdu: "روٹی", calories: 120, protein: 4, carbs: 23, fat: 1.5, servingSize: "1 roti", category: "Breads" },
  { name: "Naan (Plain)", nameUrdu: "نان", calories: 220, protein: 7, carbs: 40, fat: 4, servingSize: "1 naan", category: "Breads" },
  { name: "Roghni Naan", nameUrdu: "روغنی نان", calories: 280, protein: 8, carbs: 42, fat: 8, servingSize: "1 naan", category: "Breads" },
  { name: "Garlic Naan", nameUrdu: "لہسن والا نان", calories: 260, protein: 8, carbs: 42, fat: 7, servingSize: "1 naan", category: "Breads" },
  { name: "Cheese Naan", nameUrdu: "چیز نان", calories: 340, protein: 12, carbs: 44, fat: 11, servingSize: "1 naan", category: "Breads" },
  { name: "Peshawari Naan", nameUrdu: "پشاوری نان", calories: 300, protein: 7, carbs: 48, fat: 9, servingSize: "1 naan", category: "Breads" },
  { name: "Kalonji Naan", nameUrdu: "کلونجی نان", calories: 240, protein: 7, carbs: 41, fat: 5, servingSize: "1 naan", category: "Breads" },
  { name: "Aloo Paratha", nameUrdu: "آلو پراٹھا", calories: 340, protein: 7, carbs: 45, fat: 15, servingSize: "1 paratha", category: "Breads" },
  { name: "Gobi Paratha", nameUrdu: "گوبھی پراٹھا", calories: 300, protein: 8, carbs: 44, fat: 11, servingSize: "1 paratha", category: "Breads" },
  { name: "Mooli Paratha", nameUrdu: "مولی پراٹھا", calories: 280, protein: 7, carbs: 42, fat: 10, servingSize: "1 paratha", category: "Breads" },
  { name: "Paneer Paratha", nameUrdu: "پنیر پراٹھا", calories: 380, protein: 14, carbs: 44, fat: 16, servingSize: "1 paratha", category: "Breads" },
  { name: "Laccha Paratha", nameUrdu: "لچھا پراٹھا", calories: 320, protein: 7, carbs: 40, fat: 14, servingSize: "1 paratha", category: "Breads" },
  { name: "Desi Ghee Paratha", nameUrdu: "دیسی گھی پراٹھا", calories: 400, protein: 8, carbs: 44, fat: 20, servingSize: "1 paratha", category: "Breads" },
  { name: "Missi Roti", nameUrdu: "مسی روٹی", calories: 200, protein: 8, carbs: 30, fat: 6, servingSize: "1 roti", category: "Breads" },
  { name: "Makki di Roti", nameUrdu: "مکی دی روٹی", calories: 180, protein: 4, carbs: 32, fat: 4, servingSize: "1 roti", category: "Breads" },
  { name: "Puri", nameUrdu: "پوری", calories: 200, protein: 5, carbs: 24, fat: 9, servingSize: "2 puris", category: "Breads" },
  { name: "Bhatura", nameUrdu: "بھٹورا", calories: 260, protein: 6, carbs: 36, fat: 10, servingSize: "1 bhatura", category: "Breads" },
  { name: "Sheermal", nameUrdu: "شیرمال", calories: 290, protein: 6, carbs: 46, fat: 9, servingSize: "1 sheermal", category: "Breads" },
  { name: "Taftan", nameUrdu: "تافتان", calories: 250, protein: 7, carbs: 42, fat: 7, servingSize: "1 taftan", category: "Breads" },
  // ---------- Rice & Biryani ----------
  { name: "Chicken Biryani", nameUrdu: "چکن بریانی", calories: 650, protein: 28, carbs: 75, fat: 22, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Beef Biryani", nameUrdu: "بیف بریانی", calories: 720, protein: 30, carbs: 74, fat: 28, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Mutton Biryani", nameUrdu: "مٹن بریانی", calories: 780, protein: 32, carbs: 72, fat: 34, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Vegetable Biryani", nameUrdu: "سبزی بریانی", calories: 480, protein: 12, carbs: 78, fat: 14, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Egg Biryani", nameUrdu: "انڈہ بریانی", calories: 520, protein: 18, carbs: 72, fat: 18, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Fish Biryani", nameUrdu: "فش بریانی", calories: 600, protein: 30, carbs: 70, fat: 20, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Sindhi Biryani", nameUrdu: "سندھی بریانی", calories: 700, protein: 29, carbs: 74, fat: 26, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Chicken Pulao", nameUrdu: "چکن پلاؤ", calories: 560, protein: 26, carbs: 68, fat: 18, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Beef Pulao", nameUrdu: "بیف پلاؤ", calories: 620, protein: 28, carbs: 66, fat: 24, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Mutton Pulao", nameUrdu: "مٹن پلاؤ", calories: 660, protein: 30, carbs: 66, fat: 26, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Kabuli Pulao", nameUrdu: "کابلی پلاؤ", calories: 640, protein: 24, carbs: 70, fat: 26, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Zeera Rice", nameUrdu: "زیرہ چاول", calories: 380, protein: 8, carbs: 72, fat: 8, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Desi Fried Rice", nameUrdu: "دیسی فرائیڈ رائس", calories: 450, protein: 10, carbs: 74, fat: 14, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Rajma Chawal", nameUrdu: "راجما چاول", calories: 580, protein: 20, carbs: 88, fat: 10, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Daal Chawal", nameUrdu: "دال چاول", calories: 520, protein: 18, carbs: 84, fat: 10, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Khichdi", nameUrdu: "کھچڑی", calories: 420, protein: 16, carbs: 68, fat: 10, servingSize: "1 bowl", category: "Rice & Biryani" },
  { name: "Lemon Rice", nameUrdu: "لیموں چاول", calories: 400, protein: 8, carbs: 70, fat: 12, servingSize: "1 plate", category: "Rice & Biryani" },
  { name: "Curd Rice", nameUrdu: "دہی چاول", calories: 350, protein: 12, carbs: 52, fat: 10, servingSize: "1 bowl", category: "Rice & Biryani" },
  { name: "Tahari", nameUrdu: "تہری", calories: 520, protein: 16, carbs: 72, fat: 18, servingSize: "1 plate", category: "Rice & Biryani" },
  // ---------- Dals & Legumes ----------
  { name: "Daal Makhani", nameUrdu: "دال مکھنی", calories: 380, protein: 14, carbs: 38, fat: 18, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Daal Tadka", nameUrdu: "دال تڑکا", calories: 280, protein: 14, carbs: 34, fat: 12, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Daal Fry", nameUrdu: "دال فرائی", calories: 320, protein: 13, carbs: 34, fat: 14, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Chana Daal", nameUrdu: "چنا دال", calories: 300, protein: 16, carbs: 40, fat: 8, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Moong Daal", nameUrdu: "مونگ دال", calories: 240, protein: 16, carbs: 34, fat: 5, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Masoor Daal", nameUrdu: "مسور دال", calories: 250, protein: 15, carbs: 36, fat: 6, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Maash Daal (Urad)", nameUrdu: "ماش کی دال", calories: 290, protein: 14, carbs: 40, fat: 7, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Kala Chana Curry", nameUrdu: "کالے چنے", calories: 320, protein: 15, carbs: 44, fat: 8, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Safed Chana (Chole)", nameUrdu: "سفید چنے", calories: 340, protein: 14, carbs: 46, fat: 9, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Rajma", nameUrdu: "راجما", calories: 330, protein: 16, carbs: 52, fat: 7, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Lobia Curry", nameUrdu: "لوبیا", calories: 300, protein: 14, carbs: 48, fat: 6, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Chana Daal Gosht", nameUrdu: "چنا دال گوشت", calories: 480, protein: 30, carbs: 38, fat: 22, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Dalcha", nameUrdu: "دلچہ", calories: 360, protein: 20, carbs: 40, fat: 14, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Haleem", nameUrdu: "حلیم", calories: 420, protein: 25, carbs: 48, fat: 14, servingSize: "1 bowl", category: "Dals & Legumes" },
  { name: "Daal + 2 Roti", nameUrdu: "دال روٹی", calories: 480, protein: 18, carbs: 70, fat: 12, servingSize: "1 bowl daal + 2 roti", category: "Dals & Legumes" },
  // ---------- Chicken Curries ----------
  { name: "Chicken Karahi", nameUrdu: "چکن کڑاہی", calories: 550, protein: 38, carbs: 12, fat: 40, servingSize: "half karahi", category: "Chicken Curries" },
  { name: "Desi Chicken Curry", nameUrdu: "دیسی چکن سالن", calories: 480, protein: 36, carbs: 10, fat: 32, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Butter Chicken", nameUrdu: "بٹر چکن", calories: 620, protein: 34, carbs: 16, fat: 44, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Handi", nameUrdu: "چکن ہانڈی", calories: 580, protein: 36, carbs: 14, fat: 42, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Korma", nameUrdu: "چکن قورمہ", calories: 560, protein: 34, carbs: 14, fat: 40, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Jalfrezi", nameUrdu: "چکن جلفریزی", calories: 420, protein: 38, carbs: 14, fat: 22, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Tikka Masala", nameUrdu: "چکن ٹکا مسالہ", calories: 500, protein: 38, carbs: 16, fat: 30, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "White Chicken Karahi", nameUrdu: "وائٹ چکن کڑاہی", calories: 590, protein: 36, carbs: 12, fat: 44, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Achari Chicken", nameUrdu: "اچاری چکن", calories: 470, protein: 36, carbs: 12, fat: 30, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Balti", nameUrdu: "چکن بالٹی", calories: 450, protein: 36, carbs: 12, fat: 28, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Do Pyaza", nameUrdu: "چکن دو پیازہ", calories: 460, protein: 35, carbs: 16, fat: 28, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Saag", nameUrdu: "چکن ساگ", calories: 440, protein: 36, carbs: 12, fat: 26, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Stew", nameUrdu: "چکن اسٹیو", calories: 380, protein: 34, carbs: 12, fat: 20, servingSize: "1 bowl", category: "Chicken Curries" },
  { name: "Chicken Malai Boti Curry", nameUrdu: "ملائی بوٹی سالن", calories: 520, protein: 38, carbs: 10, fat: 36, servingSize: "1 bowl", category: "Chicken Curries" },
  // ---------- Meat Curries ----------
  { name: "Mutton Karahi", nameUrdu: "مٹن کڑاہی", calories: 650, protein: 40, carbs: 12, fat: 48, servingSize: "half karahi", category: "Meat Curries" },
  { name: "Beef Karahi", nameUrdu: "بیف کڑاہی", calories: 600, protein: 42, carbs: 12, fat: 42, servingSize: "half karahi", category: "Meat Curries" },
  { name: "Nihari", nameUrdu: "نہاری", calories: 620, protein: 32, carbs: 14, fat: 46, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Nihari + Naan", nameUrdu: "نہاری نان", calories: 720, protein: 32, carbs: 58, fat: 34, servingSize: "1 bowl + 1 naan", category: "Meat Curries" },
  { name: "Mutton Korma", nameUrdu: "مٹن قورمہ", calories: 640, protein: 38, carbs: 14, fat: 46, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Beef Korma", nameUrdu: "بیف قورمہ", calories: 600, protein: 40, carbs: 14, fat: 40, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Mutton Roghan Josh", nameUrdu: "روغن جوش", calories: 620, protein: 38, carbs: 12, fat: 44, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Beef Bihari", nameUrdu: "بیہاری بوٹی", calories: 520, protein: 42, carbs: 10, fat: 32, servingSize: "1 plate", category: "Meat Curries" },
  { name: "Mutton Paya", nameUrdu: "مٹن پائے", calories: 580, protein: 36, carbs: 8, fat: 44, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Beef Paya", nameUrdu: "بیف پائے", calories: 540, protein: 38, carbs: 8, fat: 38, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Mutton Qeema", nameUrdu: "مٹن قیمہ", calories: 480, protein: 34, carbs: 10, fat: 34, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Beef Qeema", nameUrdu: "بیف قیمہ", calories: 440, protein: 36, carbs: 10, fat: 28, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Keema Aloo", nameUrdu: "قیمہ آلو", calories: 460, protein: 32, carbs: 22, fat: 28, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Keema Matar", nameUrdu: "قیمہ مٹر", calories: 470, protein: 33, carbs: 24, fat: 27, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Mutton Handi", nameUrdu: "مٹن ہانڈی", calories: 660, protein: 40, carbs: 14, fat: 48, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Mutton Do Pyaza", nameUrdu: "مٹن دو پیازہ", calories: 600, protein: 38, carbs: 16, fat: 42, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Beef Pasanday", nameUrdu: "بیف پسندے", calories: 560, protein: 40, carbs: 12, fat: 38, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Hunter Beef", nameUrdu: "ہنٹر بیف", calories: 280, protein: 40, carbs: 4, fat: 12, servingSize: "4 slices", category: "Meat Curries" },
  { name: "Saag Gosht", nameUrdu: "ساگ گوشت", calories: 520, protein: 34, carbs: 16, fat: 34, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Karela Gosht", nameUrdu: "کریلا گوشت", calories: 460, protein: 32, carbs: 14, fat: 30, servingSize: "1 bowl", category: "Meat Curries" },
  { name: "Arvi Gosht", nameUrdu: "اروی گوشت", calories: 480, protein: 30, carbs: 30, fat: 26, servingSize: "1 bowl", category: "Meat Curries" },
  // ---------- Vegetables & Paneer ----------
  { name: "Palak Paneer", nameUrdu: "پالک پنیر", calories: 380, protein: 18, carbs: 22, fat: 26, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Palak Paneer + 2 Roti", nameUrdu: "پالک پنیر روٹی", calories: 520, protein: 20, carbs: 55, fat: 24, servingSize: "1 bowl + 2 roti", category: "Vegetables & Paneer" },
  { name: "Shahi Paneer", nameUrdu: "شاہی پنیر", calories: 460, protein: 16, carbs: 20, fat: 36, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Paneer Butter Masala", nameUrdu: "پنیر بٹر مسالہ", calories: 480, protein: 17, carbs: 18, fat: 38, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Paneer Tikka Masala", nameUrdu: "پنیر ٹکا مسالہ", calories: 420, protein: 20, carbs: 16, fat: 30, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Paneer Bhurji", nameUrdu: "پنیر بھرجی", calories: 320, protein: 18, carbs: 10, fat: 24, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Malai Kofta", nameUrdu: "ملائی کوفتہ", calories: 440, protein: 14, carbs: 28, fat: 32, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Kofta Curry", nameUrdu: "کوفتہ سالن", calories: 480, protein: 32, carbs: 18, fat: 32, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Aloo Gobi", nameUrdu: "آلو گوبھی", calories: 260, protein: 8, carbs: 34, fat: 12, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Aloo Matar", nameUrdu: "آلو مٹر", calories: 280, protein: 10, carbs: 38, fat: 10, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Aloo Palak", nameUrdu: "آلو پالک", calories: 240, protein: 8, carbs: 30, fat: 12, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Gobi Matar", nameUrdu: "گوبھی مٹر", calories: 220, protein: 8, carbs: 28, fat: 10, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Bhindi Masala", nameUrdu: "بھنڈی مسالہ", calories: 240, protein: 8, carbs: 24, fat: 14, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Baingan Bharta", nameUrdu: "بینگن بھرتہ", calories: 220, protein: 7, carbs: 22, fat: 14, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Mixed Sabzi", nameUrdu: "مکس سبزی", calories: 200, protein: 7, carbs: 26, fat: 10, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Sarson da Saag", nameUrdu: "سرسوں دا ساگ", calories: 280, protein: 10, carbs: 26, fat: 16, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  { name: "Tinda Masala", nameUrdu: "ٹینڈا مسالہ", calories: 180, protein: 6, carbs: 20, fat: 10, servingSize: "1 bowl", category: "Vegetables & Paneer" },
  // ---------- Kebabs & Grills ----------
  { name: "Chicken Tikka", nameUrdu: "چکن ٹکا", calories: 380, protein: 42, carbs: 6, fat: 18, servingSize: "2 pieces", category: "Kebabs & Grills" },
  { name: "Chicken Tikka Leg", nameUrdu: "ٹکا لیگ پیس", calories: 300, protein: 38, carbs: 4, fat: 14, servingSize: "1 piece", category: "Kebabs & Grills" },
  { name: "Seekh Kebab", nameUrdu: "سیخ کباب", calories: 450, protein: 36, carbs: 8, fat: 28, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Beef Seekh Kebab", nameUrdu: "بیف سیخ کباب", calories: 480, protein: 38, carbs: 8, fat: 32, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Mutton Seekh Kebab", nameUrdu: "مٹن سیخ کباب", calories: 520, protein: 38, carbs: 8, fat: 36, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Gilafi Seekh Kebab", nameUrdu: "گلافی سیخ کباب", calories: 470, protein: 37, carbs: 9, fat: 30, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Chicken Malai Boti", nameUrdu: "چکن ملائی بوٹی", calories: 420, protein: 40, carbs: 8, fat: 24, servingSize: "6 pieces", category: "Kebabs & Grills" },
  { name: "Chicken Boti", nameUrdu: "چکن بوٹی", calories: 400, protein: 40, carbs: 6, fat: 22, servingSize: "6 pieces", category: "Kebabs & Grills" },
  { name: "Beef Boti", nameUrdu: "بیف بوٹی", calories: 460, protein: 40, carbs: 6, fat: 30, servingSize: "6 pieces", category: "Kebabs & Grills" },
  { name: "Reshmi Kebab", nameUrdu: "ریشمی کباب", calories: 440, protein: 38, carbs: 10, fat: 26, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Chapli Kebab", nameUrdu: "چپلی کباب", calories: 380, protein: 26, carbs: 16, fat: 24, servingSize: "2 pieces", category: "Kebabs & Grills" },
  { name: "Shami Kebab", nameUrdu: "شامی کباب", calories: 220, protein: 18, carbs: 14, fat: 10, servingSize: "2 pieces", category: "Kebabs & Grills" },
  { name: "Tandoori Chicken", nameUrdu: "تندوری چکن", calories: 420, protein: 46, carbs: 6, fat: 20, servingSize: "half chicken", category: "Kebabs & Grills" },
  { name: "Tandoori Wings", nameUrdu: "تندوری ونگز", calories: 380, protein: 36, carbs: 6, fat: 22, servingSize: "6 pieces", category: "Kebabs & Grills" },
  { name: "Desi Chicken Wings", nameUrdu: "دیسی چکن ونگز", calories: 460, protein: 34, carbs: 8, fat: 32, servingSize: "6 pieces", category: "Kebabs & Grills" },
  { name: "Sajji", nameUrdu: "سجی", calories: 580, protein: 48, carbs: 4, fat: 40, servingSize: "quarter chicken", category: "Kebabs & Grills" },
  { name: "Fish Tikka", nameUrdu: "فش ٹکا", calories: 320, protein: 38, carbs: 8, fat: 12, servingSize: "4 pieces", category: "Kebabs & Grills" },
  { name: "Chicken Chargha", nameUrdu: "چکن چرغہ", calories: 680, protein: 44, carbs: 8, fat: 50, servingSize: "half chicken", category: "Kebabs & Grills" },
  { name: "Mutton Chanp (Ribs)", nameUrdu: "مٹن چانپ", calories: 620, protein: 40, carbs: 6, fat: 48, servingSize: "4 pieces", category: "Kebabs & Grills" },
  // ---------- Breakfast ----------
  { name: "Halwa Puri Set", nameUrdu: "حلوہ پوری", calories: 650, protein: 12, carbs: 88, fat: 26, servingSize: "1 set (2 puri + halwa)", category: "Breakfast" },
  { name: "Suji Halwa", nameUrdu: "سوجی حلوہ", calories: 380, protein: 6, carbs: 62, fat: 16, servingSize: "1 bowl", category: "Breakfast" },
  { name: "Anda Paratha", nameUrdu: "انڈہ پراٹھا", calories: 420, protein: 14, carbs: 44, fat: 20, servingSize: "1 paratha + 1 egg", category: "Breakfast" },
  { name: "Desi Omelette", nameUrdu: "دیسی آملیٹ", calories: 280, protein: 16, carbs: 4, fat: 22, servingSize: "2 eggs", category: "Breakfast" },
  { name: "Fried Egg", nameUrdu: "فرائی انڈہ", calories: 180, protein: 12, carbs: 2, fat: 14, servingSize: "2 eggs", category: "Breakfast" },
  { name: "Boiled Egg", nameUrdu: "ابلا انڈہ", calories: 140, protein: 12, carbs: 2, fat: 10, servingSize: "2 eggs", category: "Breakfast" },
  { name: "Maghaz (Brain Masala)", nameUrdu: "مغز", calories: 380, protein: 22, carbs: 6, fat: 30, servingSize: "1 plate", category: "Breakfast" },
  { name: "Siri Paya", nameUrdu: "سری پائے", calories: 520, protein: 34, carbs: 8, fat: 40, servingSize: "1 bowl", category: "Breakfast" },
  { name: "Kata Kat", nameUrdu: "کٹا کٹ", calories: 520, protein: 36, carbs: 8, fat: 38, servingSize: "1 plate", category: "Breakfast" },
  { name: "Sweet Lassi", nameUrdu: "میٹھی لسی", calories: 320, protein: 12, carbs: 44, fat: 10, servingSize: "1 glass", category: "Breakfast" },
  { name: "Namkeen Lassi", nameUrdu: "نمکین لسی", calories: 220, protein: 14, carbs: 18, fat: 12, servingSize: "1 glass", category: "Breakfast" },
  { name: "Doodh Patti", nameUrdu: "دودھ پتی", calories: 160, protein: 8, carbs: 20, fat: 6, servingSize: "1 cup", category: "Breakfast" },
  { name: "Kashmiri Chai", nameUrdu: "کشمیری چائے", calories: 180, protein: 6, carbs: 22, fat: 8, servingSize: "1 cup", category: "Breakfast" },
  { name: "Chana Chaat", nameUrdu: "چنا چاٹ", calories: 260, protein: 12, carbs: 40, fat: 6, servingSize: "1 bowl", category: "Breakfast" },
  // ---------- Snacks & Street Food ----------
  { name: "Samosa", nameUrdu: "سموسہ", calories: 260, protein: 6, carbs: 28, fat: 14, servingSize: "2 pieces", category: "Snacks & Street Food" },
  { name: "Chicken Samosa", nameUrdu: "چکن سموسہ", calories: 300, protein: 14, carbs: 26, fat: 14, servingSize: "2 pieces", category: "Snacks & Street Food" },
  { name: "Keema Samosa", nameUrdu: "قیمہ سموسہ", calories: 320, protein: 16, carbs: 26, fat: 16, servingSize: "2 pieces", category: "Snacks & Street Food" },
  { name: "Mixed Pakora", nameUrdu: "مکس پکوڑے", calories: 320, protein: 8, carbs: 32, fat: 18, servingSize: "6 pieces", category: "Snacks & Street Food" },
  { name: "Chicken Pakora", nameUrdu: "چکن پکوڑے", calories: 380, protein: 22, carbs: 24, fat: 20, servingSize: "6 pieces", category: "Snacks & Street Food" },
  { name: "Fish Pakora", nameUrdu: "فش پکوڑے", calories: 340, protein: 24, carbs: 22, fat: 18, servingSize: "6 pieces", category: "Snacks & Street Food" },
  { name: "Dahi Bhalla", nameUrdu: "دہی بھلے", calories: 280, protein: 10, carbs: 40, fat: 8, servingSize: "1 plate", category: "Snacks & Street Food" },
  { name: "Gol Gappa", nameUrdu: "گول گپے", calories: 220, protein: 6, carbs: 38, fat: 6, servingSize: "6 pieces", category: "Snacks & Street Food" },
  { name: "Papdi Chaat", nameUrdu: "پاپڑی چاٹ", calories: 300, protein: 8, carbs: 44, fat: 10, servingSize: "1 plate", category: "Snacks & Street Food" },
  { name: "Dahi Puri", nameUrdu: "دہی پوری", calories: 240, protein: 8, carbs: 36, fat: 8, servingSize: "6 pieces", category: "Snacks & Street Food" },
  { name: "Aloo Tikki", nameUrdu: "آلو ٹکی", calories: 280, protein: 6, carbs: 40, fat: 12, servingSize: "2 pieces", category: "Snacks & Street Food" },
  { name: "Samosa Chaat", nameUrdu: "سموسہ چاٹ", calories: 380, protein: 10, carbs: 52, fat: 14, servingSize: "1 plate", category: "Snacks & Street Food" },
  { name: "Bun Kebab", nameUrdu: "بن کباب", calories: 420, protein: 16, carbs: 44, fat: 18, servingSize: "1 burger", category: "Snacks & Street Food" },
  { name: "Shami Burger", nameUrdu: "شامی برگر", calories: 380, protein: 18, carbs: 40, fat: 14, servingSize: "1 burger", category: "Snacks & Street Food" },
  { name: "Chicken Roll Paratha", nameUrdu: "چکن رول پراٹھا", calories: 520, protein: 28, carbs: 48, fat: 22, servingSize: "1 roll", category: "Snacks & Street Food" },
  { name: "Beef Roll Paratha", nameUrdu: "بیف رول پراٹھا", calories: 560, protein: 30, carbs: 48, fat: 26, servingSize: "1 roll", category: "Snacks & Street Food" },
  { name: "Chicken Shawarma", nameUrdu: "چکن شاورما", calories: 520, protein: 30, carbs: 44, fat: 20, servingSize: "1 roll", category: "Snacks & Street Food" },
  { name: "Bhel Puri", nameUrdu: "بھیل پوری", calories: 220, protein: 6, carbs: 40, fat: 6, servingSize: "1 plate", category: "Snacks & Street Food" },
  { name: "Fruit Chaat", nameUrdu: "فروٹ چاٹ", calories: 180, protein: 3, carbs: 44, fat: 2, servingSize: "1 bowl", category: "Snacks & Street Food" },
  { name: "Daal Moth", nameUrdu: "دال موٹھ", calories: 200, protein: 12, carbs: 30, fat: 4, servingSize: "1 bowl", category: "Snacks & Street Food" },
  { name: "Nimko Mix", nameUrdu: "نمکو مکس", calories: 280, protein: 8, carbs: 30, fat: 16, servingSize: "1 bowl", category: "Snacks & Street Food" },
  { name: "Masala Fries", nameUrdu: "مصالحہ فرائز", calories: 420, protein: 6, carbs: 52, fat: 22, servingSize: "1 plate", category: "Snacks & Street Food" },
  { name: "Spring Roll", nameUrdu: "اسپرنگ رول", calories: 260, protein: 8, carbs: 30, fat: 12, servingSize: "2 pieces", category: "Snacks & Street Food" },
  { name: "Loaded Fries", nameUrdu: "لوڈڈ فرائز", calories: 620, protein: 18, carbs: 56, fat: 36, servingSize: "1 plate", category: "Snacks & Street Food" },
  // ---------- Desserts & Sweets ----------
  { name: "Gulab Jamun", nameUrdu: "گلاب جامن", calories: 300, protein: 5, carbs: 52, fat: 10, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Rasmalai", nameUrdu: "رس ملائی", calories: 320, protein: 10, carbs: 44, fat: 10, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Kheer", nameUrdu: "کھیر", calories: 280, protein: 9, carbs: 44, fat: 8, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Firni", nameUrdu: "فرنی", calories: 300, protein: 8, carbs: 50, fat: 8, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Gajar ka Halwa", nameUrdu: "گاجر کا حلوہ", calories: 360, protein: 7, carbs: 58, fat: 14, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Zarda", nameUrdu: "زردہ", calories: 380, protein: 6, carbs: 72, fat: 10, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Shahi Tukray", nameUrdu: "شاہی ٹکڑے", calories: 420, protein: 9, carbs: 58, fat: 18, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Rasgulla", nameUrdu: "رس گلہ", calories: 240, protein: 8, carbs: 48, fat: 4, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Milk Barfi", nameUrdu: "دودھ برفی", calories: 320, protein: 8, carbs: 48, fat: 12, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Pista Barfi", nameUrdu: "پستہ برفی", calories: 340, protein: 9, carbs: 46, fat: 14, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Jalebi", nameUrdu: "جلیبی", calories: 340, protein: 4, carbs: 68, fat: 10, servingSize: "4 pieces", category: "Desserts & Sweets" },
  { name: "Kulfi", nameUrdu: "قلفی", calories: 260, protein: 7, carbs: 38, fat: 10, servingSize: "1 kulfi", category: "Desserts & Sweets" },
  { name: "Falooda", nameUrdu: "فالودہ", calories: 480, protein: 10, carbs: 84, fat: 12, servingSize: "1 glass", category: "Desserts & Sweets" },
  { name: "Rabri", nameUrdu: "ربڑی", calories: 380, protein: 12, carbs: 44, fat: 16, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Sheer Khurma", nameUrdu: "شیر خورمہ", calories: 420, protein: 10, carbs: 58, fat: 16, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Doodh Dulari", nameUrdu: "دودھ دلاری", calories: 450, protein: 9, carbs: 68, fat: 14, servingSize: "1 bowl", category: "Desserts & Sweets" },
  { name: "Cham Cham", nameUrdu: "چم چم", calories: 280, protein: 9, carbs: 52, fat: 6, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Motichoor Ladoo", nameUrdu: "موتی چور لڈو", calories: 320, protein: 5, carbs: 52, fat: 12, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Besan Ladoo", nameUrdu: "بیسن لڈو", calories: 340, protein: 7, carbs: 44, fat: 16, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Coconut Ladoo", nameUrdu: "ناریل لڈو", calories: 300, protein: 5, carbs: 40, fat: 14, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Balushahi", nameUrdu: "بالوشاہی", calories: 380, protein: 5, carbs: 60, fat: 14, servingSize: "2 pieces", category: "Desserts & Sweets" },
  { name: "Kalakand", nameUrdu: "کلاکند", calories: 300, protein: 10, carbs: 46, fat: 10, servingSize: "2 pieces", category: "Desserts & Sweets" },
  // ---------- Drinks & Beverages ----------
  { name: "Mango Lassi", nameUrdu: "مینگو لسی", calories: 380, protein: 11, carbs: 62, fat: 9, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Mango Shake", nameUrdu: "مینگو شیک", calories: 420, protein: 10, carbs: 68, fat: 10, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Banana Shake", nameUrdu: "بنانا شیک", calories: 360, protein: 11, carbs: 58, fat: 9, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Badam Milk", nameUrdu: "بادام دودھ", calories: 300, protein: 11, carbs: 34, fat: 12, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Thandai", nameUrdu: "ٹھنڈائی", calories: 280, protein: 9, carbs: 36, fat: 10, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Rooh Afza Milk", nameUrdu: "روح افزا دودھ", calories: 240, protein: 8, carbs: 46, fat: 4, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Sugarcane Juice", nameUrdu: "گنے کا رس", calories: 220, protein: 1, carbs: 56, fat: 0.5, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Falsa Juice", nameUrdu: "فالسہ جوس", calories: 140, protein: 1, carbs: 34, fat: 1, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Sattu Drink", nameUrdu: "ستو", calories: 200, protein: 10, carbs: 34, fat: 3, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Mint Margarita", nameUrdu: "منٹ مارگریٹا", calories: 120, protein: 1, carbs: 30, fat: 0.5, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Doodh Soda", nameUrdu: "دودھ سوڈا", calories: 260, protein: 9, carbs: 44, fat: 5, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Kachi Lassi", nameUrdu: "کچی لسی", calories: 180, protein: 12, carbs: 22, fat: 6, servingSize: "1 glass", category: "Drinks & Beverages" },
  { name: "Fresh Orange Juice", nameUrdu: "اورنج جوس", calories: 160, protein: 2, carbs: 38, fat: 1, servingSize: "1 glass", category: "Drinks & Beverages" },
  // ---------- Dahi, Raita & Sides ----------
  { name: "Plain Dahi", nameUrdu: "سادہ دہی", calories: 140, protein: 9, carbs: 12, fat: 6, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Mint Raita", nameUrdu: "پودینہ رائتہ", calories: 120, protein: 6, carbs: 10, fat: 6, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Cucumber Raita", nameUrdu: "کھیرا رائتہ", calories: 110, protein: 6, carbs: 10, fat: 5, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Boondi Raita", nameUrdu: "بوندی رائتہ", calories: 180, protein: 6, carbs: 18, fat: 9, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Masala Dahi", nameUrdu: "مصالحہ دہی", calories: 150, protein: 9, carbs: 13, fat: 6, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Mixed Salad", nameUrdu: "مکس سلاد", calories: 60, protein: 2, carbs: 12, fat: 1, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Kachumber", nameUrdu: "کچومبر", calories: 70, protein: 2, carbs: 14, fat: 1, servingSize: "1 bowl", category: "Dahi, Raita & Sides" },
  { name: "Green Chutney", nameUrdu: "ہری چٹنی", calories: 40, protein: 1, carbs: 8, fat: 1, servingSize: "2 tbsp", category: "Dahi, Raita & Sides" },
  { name: "Imli Chutney", nameUrdu: "املی چٹنی", calories: 90, protein: 0.5, carbs: 22, fat: 0.5, servingSize: "2 tbsp", category: "Dahi, Raita & Sides" },
  { name: "Mixed Achar", nameUrdu: "مکس اچار", calories: 60, protein: 1, carbs: 6, fat: 4, servingSize: "2 tbsp", category: "Dahi, Raita & Sides" },
  { name: "Papad", nameUrdu: "پاپڑ", calories: 120, protein: 5, carbs: 20, fat: 3, servingSize: "2 pieces", category: "Dahi, Raita & Sides" },
  { name: "Roasted Papad", nameUrdu: "روسٹڈ پاپڑ", calories: 90, protein: 5, carbs: 18, fat: 1, servingSize: "2 pieces", category: "Dahi, Raita & Sides" },
];
